language: go
go:
  - "1.15"
before_install:
  - go get github.com/stretchr/testify
  - go get github.com/client9/misspell/cmd/misspell
before_script:
  - go vet .
script:
  - go test -v
  - misspell -locale US -error *.md *.go